import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { generatePhpOverrideIni, writePhpOverride } from "./php.js";

describe("php overrides", () => {
  let tempDir: string;

  beforeEach(() => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "procsi-php-test-"));
  });

  afterEach(() => {
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  describe("generatePhpOverrideIni", () => {
    it("should contain curl.cainfo directive", () => {
      const ini = generatePhpOverrideIni("/path/to/ca.pem");
      expect(ini).toContain("curl.cainfo=/path/to/ca.pem");
    });

    it("should contain openssl.cafile directive", () => {
      const ini = generatePhpOverrideIni("/path/to/ca.pem");
      expect(ini).toContain("openssl.cafile=/path/to/ca.pem");
    });

    it("should embed the CA cert path correctly", () => {
      const caCertPath = "/home/user/.procsi/ca.pem";
      const ini = generatePhpOverrideIni(caCertPath);
      expect(ini).toContain(`curl.cainfo=${caCertPath}`);
      expect(ini).toContain(`openssl.cafile=${caCertPath}`);
    });

    it("should handle paths with spaces", () => {
      const caCertPath = "/path with spaces/.procsi/ca.pem";
      const ini = generatePhpOverrideIni(caCertPath);
      expect(ini).toContain(`curl.cainfo=${caCertPath}`);
      expect(ini).toContain(`openssl.cafile=${caCertPath}`);
    });

    it("should include a comment explaining purpose", () => {
      const ini = generatePhpOverrideIni("/path/to/ca.pem");
      expect(ini).toContain("; Generated by procsi");
    });
  });

  describe("writePhpOverride", () => {
    it("should create the INI file on disk", () => {
      const outputDir = path.join(tempDir, "php");
      const caCertPath = "/path/to/ca.pem";

      writePhpOverride(outputDir, caCertPath);

      const iniPath = path.join(outputDir, "procsi.ini");
      expect(fs.existsSync(iniPath)).toBe(true);

      const content = fs.readFileSync(iniPath, "utf-8");
      expect(content).toContain("curl.cainfo=/path/to/ca.pem");
      expect(content).toContain("openssl.cafile=/path/to/ca.pem");
    });

    it("should create parent directories", () => {
      const outputDir = path.join(tempDir, "nested", "php", "config");
      const caCertPath = "/path/to/ca.pem";

      writePhpOverride(outputDir, caCertPath);

      expect(fs.existsSync(outputDir)).toBe(true);
      const iniPath = path.join(outputDir, "procsi.ini");
      expect(fs.existsSync(iniPath)).toBe(true);
    });

    it("should return the directory path", () => {
      const outputDir = path.join(tempDir, "php");
      const caCertPath = "/path/to/ca.pem";

      const result = writePhpOverride(outputDir, caCertPath);

      expect(result).toBe(outputDir);
    });

    it("should handle paths with special characters", () => {
      const outputDir = path.join(tempDir, "php config");
      const caCertPath = "/path with spaces/.procsi/ca.pem";

      writePhpOverride(outputDir, caCertPath);

      const iniPath = path.join(outputDir, "procsi.ini");
      expect(fs.existsSync(iniPath)).toBe(true);

      const content = fs.readFileSync(iniPath, "utf-8");
      expect(content).toContain(caCertPath);
    });
  });
});
