import * as fs from "node:fs";
import * as path from "node:path";

/**
 * Generate the contents of `sitecustomize.py` that patches Python
 * HTTP clients to use the procsi proxy and trust the CA certificate.
 *
 * The script patches httplib2 to respect HTTP_PROXY env vars and
 * use the procsi CA certificate. All patching is wrapped in try/except
 * so failures never break the user's Python environment.
 *
 * The caCertPath is embedded as a string literal in the generated Python.
 */
export function generatePythonOverrideScript(caCertPath: string): string {
  // Escape the path for Python string literals (backslashes and quotes)
  const escapedCaCertPath = caCertPath.replace(/\\/g, "\\\\").replace(/'/g, "\\'");

  return [
    "# Generated by procsi — patches Python HTTP clients to use the proxy",
    "",
    "import os",
    "",
    "# Patch httplib2 to trust procsi CA certificate and use proxy",
    "try:",
    "    import httplib2",
    "",
    "    # Override CA_CERTS to trust procsi's CA",
    `    httplib2.CA_CERTS = '${escapedCaCertPath}'`,
    "",
    "    # Patch Http.__init__ to inject proxy from HTTP_PROXY env var",
    "    _original_httplib2_init = httplib2.Http.__init__",
    "",
    "    def _patched_httplib2_init(self, *args, **kwargs):",
    "        # If proxy_info not provided and HTTP_PROXY env var exists, inject it",
    "        if 'proxy_info' not in kwargs:",
    "            http_proxy = os.environ.get('HTTP_PROXY') or os.environ.get('http_proxy')",
    "            if http_proxy:",
    "                try:",
    "                    from httplib2 import socks",
    "                    import urllib.parse",
    "                    parsed = urllib.parse.urlparse(http_proxy)",
    "                    kwargs['proxy_info'] = httplib2.ProxyInfo(",
    "                        socks.PROXY_TYPE_HTTP,",
    "                        parsed.hostname,",
    "                        parsed.port or 8080,",
    "                    )",
    "                except Exception:",
    "                    pass  # Silently ignore proxy injection failures",
    "        _original_httplib2_init(self, *args, **kwargs)",
    "",
    "    httplib2.Http.__init__ = _patched_httplib2_init",
    "",
    "except Exception:",
    "    pass  # Silently ignore if httplib2 is not available or patching fails",
    "",
  ].join("\n");
}

/**
 * Write the `sitecustomize.py` override script to the given directory.
 * Creates the directory recursively if it doesn't exist.
 *
 * Returns the absolute path to the directory where the script was written.
 */
export function writePythonOverride(outputDir: string, caCertPath: string): string {
  try {
    fs.mkdirSync(outputDir, { recursive: true });
    const scriptPath = path.join(outputDir, "sitecustomize.py");
    const scriptContent = generatePythonOverrideScript(caCertPath);
    fs.writeFileSync(scriptPath, scriptContent, "utf-8");
    return outputDir;
  } catch (error) {
    throw new Error(
      `Failed to write Python override to ${outputDir}: ${error instanceof Error ? error.message : String(error)}`
    );
  }
}
