import * as fs from "node:fs";
import * as path from "node:path";

/**
 * Generate the contents of the Ruby preload script that monkey-patches
 * OpenSSL::X509::Store to add the procsi CA certificate to the default
 * certificate store.
 *
 * This ensures gems with bundled CAs (Stripe, Cloudinary, etc.) also
 * trust the proxy certificate.
 */
export function generateRubyOverrideScript(caCertPath: string): string {
  // Escape single quotes in the path for Ruby string literal
  const escapedCaCertPath = caCertPath.replace(/'/g, "\\'");

  return [
    "# Generated by procsi — ensures Ruby trusts the proxy CA certificate",
    "",
    "begin",
    "  require 'openssl'",
    "",
    "  # Store the original set_default_paths method",
    "  module OpenSSL",
    "    module X509",
    "      class Store",
    "        alias_method :original_set_default_paths, :set_default_paths",
    "",
    "        # Monkey-patch to add procsi CA cert alongside system certs",
    "        def set_default_paths",
    "          original_set_default_paths",
    `          procsi_ca_path = '${escapedCaCertPath}'`,
    "          if File.exist?(procsi_ca_path)",
    "            add_file(procsi_ca_path)",
    "          end",
    "        end",
    "      end",
    "    end",
    "  end",
    "rescue => e",
    "  # Silently fail to avoid breaking the user's Ruby application",
    "end",
    "",
  ].join("\n");
}

/**
 * Write the Ruby override script to the given directory.
 * Creates the directory recursively if needed.
 *
 * Returns the absolute path to the written file (not the directory).
 */
export function writeRubyOverride(outputDir: string, caCertPath: string): string {
  fs.mkdirSync(outputDir, { recursive: true });
  const outputPath = path.join(outputDir, "procsi_intercept.rb");
  fs.writeFileSync(outputPath, generateRubyOverrideScript(caCertPath), "utf-8");
  return outputPath;
}
